travis:
  secure:
    BINSTAR_TOKEN: Hnbf7TF7Be2w8O0u87OMOnmK59mnI8OQv7Nrc9a4uF2t4G6B9g8gAS3ZeETNQIk+V0mESFBr/Ss4CbqJVY4uvaZgangs8C2el7mdO2cBV8vLdRS7ndBBgeL5EpyVmiHrq1ikfLP6lPlEJp0h7mnazV6779PTrQhAKvNK0v8irLW57PAn1hLP3JvtrQXbysfvT1ouFbFFgg8PRloPKNGPlxV8eMD9AJp2Q2WarkVr+BRE7i8Q3h14ytFKGbhleJ1OIg0HjCgAHNe5Gd0UVNH3uepnA6UzzZtQRZuLRfVGa/stkKJeNLO8xCui+QArxY7V3WS3V0E2LUzHHtoV682z+n7coL2H87Ls8cJsB8uYDY8V/BssNbyS3tmsSYMtvQpNLKlxET8bUm39AtTLZaDhWAyBkMDyQLxIZZhHpL2lwz437e3Q3aKfJaYGrzLNB8P2hjZOCCKs1jyA1kqbDN/BwBPbrT3/BNjuTNgE326o/BVeUHjEG8YOqCgLg31jGrDAue3ecwy9oe2o/FqvLLszCNJKhJTZdCeeqCDN7xRN/ZKMZFyl3kiOBuNL/VOjRuZauWLfB5j4o5QOT0xZOz6SKJr5r7OMgj+TxbILOr0pxK0SPG3f5RSrGrRbdfkxgbuSVWw0TlfTNG72+MwzixlAf6816IIDF/xoYZGJUqeI1vY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
