travis:
  secure:
    BINSTAR_TOKEN: rwkYYAXML880Fewc9JqQ5XrScNiowr9RY03o2sIFlW09TYw025kqfpXpvc+jLeRdD56ctPwdh5lHIHdlWW5NY3IGBfQ5PvIzCfoKaPRA7tTahM/IvELpB05XA44mSC3Qwcspj9ryasysnEkUR/dQ1vuHIASAXIaa9hoFGkTy5VvV87jHNAj9SCj8l9ALPfQrWpYMtWIpcCJ7WCW3XF85p5UxJvgh+dDyZMkWZMlmBJHcEpj+uc3q0DWICsw3M89QKjbx0MfO0ObgTzN/7zs/9XzictIHDLabH0rJjH1B0YZO0n8PN0uDQbptKodxWevFUZIY5OAJvv1HpvBaqcoLhTnkeqS3WUB0s5UOig/0H+cj8wFdI6E4T/TMnmKWH4lY138zGy+0bbQGJDgWKeKS1JxAd4pNg6AnNFXm38/yg7mV+rK6us2pJXuRmUrDb9gliD+DgeQ396HLnKPPPVztCtN4D2NwbcUTU0dlopcQGUZtiec2y+TgakWKpaXhgF7gAuMm9IlCjH0/8MjQctL28pA0GDPuyVzR6pZahGt7cag/CWtIDRacLRN3LfhyEBCGXyLnjWzNHERvCGMetU3avcRUltLSdy50HrgdL2T8jk5PkzktgMKbLEiiPdBIZm9p22GzhcuckIjAVJknsRy9+GRurVQjHYPpq+/Cbyo361c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
