travis:
  secure:
    BINSTAR_TOKEN: lgr1Ue86vYRyMe5NNrgVVRJ9qx58Qc0CvW0Eivt+HDDmHw4ffTFirvWmHGyF7/iWvQCZeiJgbF7aARQ/KG3GvuPEw6+EHWrZzk4TZrI4SAbJML+wN09ENjoq2lL37uv4tVZcSdwDLGA3LRPJgBaNV67NGy6U5z9UVb5NSI4w+774FZtz8bJLU9nGzeiADTCLkkgTURiftEw0kIyKKWAEptcJZjnprXKMBYoAOKXvX6CUj39VIg0blf03abCJrwUbn8Nkn0MyLG3cZ838EE7scnEe/vNTvuyGROJnyFx6l3bPH1l1lKzCT7//xeMabW2MH22BLZknoJyDGAAONYHZHyLcrTo9EszOYSIM6r9n920LYdSZl5/mNXyczrjsXbxX+iEgP0m52h+ycERAHLC9feuvRf1QZtBloxP/2gCIIuqhefXFc7L5afRieTfL6t6k0Fcqt2Gdlvd9j4jvhHVbvR5XISFcshzie2qSiyEUS/saAYGwXL247VjoZeixw/Cardr/W2Jk0kvDuUo0Me0DN6A+VtsXvfTPvPxll9VKFj2yMzUcAbYn4J0cLZIVH0K4kA/E0T48R3MBO0q3qYFW1+aSaPA89furV3uR7LZmBgepqJCL4c8FqC+x9n1OK4NegT1p95KhWIqTFJUhLGMaof8D4C+RhzsyX3bRd8pdFe4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
