travis:
  secure:
    BINSTAR_TOKEN: I3/7t8QtRDmEGUMP4+v00tXB7mBsgduZLtzsJTRbtzrDy3h7Y/+vd/KU8fdeg9JdCkjCQNjY4mK7XvLOyNOZM57dxn75H6qqg97d+j2HvS0mtpRQfF1L+HTJS8OM30oXvm06L4CTsacXFpw6e9xVB3k/ezTw/hyPAXfn4dctN2CUT41edi/+hBoG28tfDasp17tHa1KouXz89ssprKiUWkjZkQW4DFjZcPLqUFc2QSMk4BErfxBXoxKdX/oyuRjwIwM2YwM53slYpt30I3Q5TCaT7x0PvPDBECn6QfpCqDqFRdUAkESXgPitGY5fDSajjAf9JwEm4ju2iJs65xO1/XSzYd+C4A+ylxkCrgAdbPU+XqlERHy9yDOHyblNbsMtuEG9zZkgclbTuomreX3rDuZGRgyP4bMuuVEzjoAlc+cIGlmXK53QDjzpas5SZfziK37I/gBWEX8uhydgGqukWOJpTv3AeI3voG8rhOj4QY4u0v7QudIYM4PdlgK2Gn3/nPRf4wIQC1h1dVcPcQRwwR/pSbjfGYQbNDM4RJ2mdCBOIuhqzjOAoeVSdR8kAtMJQBHi/3lZKN2vZpN34NEK2Cjr2icuUiLsi9p3wBHHyh1b5NEbd1lPW7rYBnBT/wHRGlZzEFj1aSBg2E41BdHtMBafU0Fd8BqCKveAsTEySAo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
