travis:
  secure:
    BINSTAR_TOKEN: qahsBPmJWm24vKn7LyNmKTZKrIrkRiWFT2tS3mhbO5+SAXaWDilWnloUqMfmGrFetQP7JMHvBluRwibhze5p2ngofwlbUKBHcr2Pau8e87xTQxDMZoCjfQGBsLXT0vw1U+onC5yHs2iOfVDmEUXIJ0Ys/SjMGXICUQX3ma0dNjYYJUKIenqeAAMUM2FJ2AT7quiS2YDZ+QD1BPvlMA8WkawKHUPPW1E7ccy4nJJQtaK6uCcZwbvFsJfBrWbY1qYA4a434NIYDdxHVcRzqaQqNICWbEowDlv0VqEh9YrafwWIUnO9vos4XYIT9qOvkbkszRPEgPyorEl957ZJi/qiuGhUXIK2TB+qFcB8/xFsVbhhwlxvjwn5Z0G/ZdJNwJ6ACnVJCoD+FZB2Jg3987WsPvLJSeYG6wu/7T9MspMi+dACn3edKcSL22ElFF5VDeRoJnFYt76ch3+h7sWgIxIAHY4JaIIze/DR/jlMF/9jzdaJtXGFW85/gRGfCu4BBf+HmE45YSviSruSmo+/Nrluwrz/2Ej+wttoMUcE9o+7xbxnBgdrnj9G5beue4rSvj4SX+l1SS5O/fPdg2KNIiklExQ5nGxOR9d+ixiPOU7ho1j60ueoE84jcwzu7sbtQJt+bWcNL539o9i3q4/HCHcZQWu+dOAs4XEV0o6Q2IHIhnU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
